name: ci-sonarcloud
on:
  pull_request:
    branchs:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latgest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test -coverageprofile=coverage.out